version: '3'

services:
  reverse-proxy:
    image: traefik:v3.3
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web
  
  api-produits:
    image: api-produits
    labels:
      - "traefik.http.routers.api-produits.rule=Host(`produits.fermesoccitane.fr`)"
      - "traefik.http.services.api-produits.loadbalancer.server.port=3000"
    networks:
      - web

  api-origine:
    image: api-origine
    labels:
      - "traefik.http.routers.api-origine.rule=Host(`origine.fermesoccitane.fr`)"
      - "traefik.http.services.api-origine.loadbalancer.server.port=8000"
    networks:
      - web

networks:
  web:
    external: false
